-- EJECUTAR ESTE SCRIPT EN SUPABASE SQL EDITOR AHORA

-- Crear tabla ordenes_toppings
CREATE TABLE IF NOT EXISTS ordenes_toppings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
    topping_id INTEGER NOT NULL REFERENCES toppings(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Crear índices
CREATE INDEX IF NOT EXISTS idx_ordenes_toppings_orden_id ON ordenes_toppings(orden_id);
CREATE INDEX IF NOT EXISTS idx_ordenes_toppings_topping_id ON ordenes_toppings(topping_id);

-- Deshabilitar RLS para desarrollo
ALTER TABLE ordenes_toppings DISABLE ROW LEVEL SECURITY;

-- Verificar que se creó correctamente
SELECT 
    'Tabla ordenes_toppings creada exitosamente' as mensaje,
    COUNT(*) as registros_iniciales 
FROM ordenes_toppings;