-- 🚨 EJECUTAR ESTE SCRIPT EN SUPABASE SQL EDITOR INMEDIATAMENTE 🚨

-- Verificar si la tabla ya existe
SELECT EXISTS (
   SELECT FROM information_schema.tables 
   WHERE table_schema = 'public' 
   AND table_name = 'ordenes_toppings'
) as tabla_existe;

-- Crear tabla ordenes_toppings si no existe
CREATE TABLE IF NOT EXISTS ordenes_toppings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
    topping_id INTEGER NOT NULL REFERENCES toppings(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Crear índices para optimización
CREATE INDEX IF NOT EXISTS idx_ordenes_toppings_orden_id ON ordenes_toppings(orden_id);
CREATE INDEX IF NOT EXISTS idx_ordenes_toppings_topping_id ON ordenes_toppings(topping_id);

-- Deshabilitar RLS para desarrollo (igual que las otras tablas)
ALTER TABLE ordenes_toppings DISABLE ROW LEVEL SECURITY;

-- Verificar que se creó correctamente
SELECT 
    'ordenes_toppings creada exitosamente ✅' as resultado,
    COUNT(*) as registros_iniciales 
FROM ordenes_toppings;

-- Verificar estructura de la tabla
SELECT 
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'ordenes_toppings' 
ORDER BY ordinal_position;