-- Create ordenes_toppings table to store toppings added to orders
-- This table tracks extra toppings that customers add to their orders

CREATE TABLE IF NOT EXISTS ordenes_toppings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
    topping_id INTEGER NOT NULL REFERENCES toppings(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_ordenes_toppings_orden_id ON ordenes_toppings(orden_id);
CREATE INDEX IF NOT EXISTS idx_ordenes_toppings_topping_id ON ordenes_toppings(topping_id);

-- Disable RLS for development (matching other tables)
ALTER TABLE ordenes_toppings DISABLE ROW LEVEL SECURITY;

-- Verify table was created correctly
SELECT 'Table ordenes_toppings created successfully' as result;
SELECT COUNT(*) as initial_count FROM ordenes_toppings;