-- 🚨 EJECUTAR INMEDIATAMENTE EN SUPABASE SQL EDITOR 🚨

-- Crear tabla ordenes_toppings
CREATE TABLE IF NOT EXISTS ordenes_toppings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
    topping_id INTEGER NOT NULL REFERENCES toppings(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Crear índices para optimización
CREATE INDEX IF NOT EXISTS idx_ordenes_toppings_orden_id ON ordenes_toppings(orden_id);
CREATE INDEX IF NOT EXISTS idx_ordenes_toppings_topping_id ON ordenes_toppings(topping_id);

-- Deshabilitar RLS para desarrollo (igual que las otras tablas)
ALTER TABLE ordenes_toppings DISABLE ROW LEVEL SECURITY;

-- Verificar creación exitosa
SELECT 'ordenes_toppings creada exitosamente ✅' as resultado;
SELECT COUNT(*) as registros_iniciales FROM ordenes_toppings;